[build]
  publish = "public"
  command = "pip install -r requirements.txt && (python3 scripts/fetch_and_build.py || python scripts/fetch_and_build.py)"
  environment = { PYTHON_VERSION = "3.10" }

[functions]
  directory = "netlify/functions"

# Scheduled Functions: 对于非 JS/TS 语言，需要在 netlify.toml 指定 cron 表达式
[[functions.scheduled]]
  name = "schedule-build"
  schedule = "0 0 * * *" # 每日 00:00 UTC 运行